@baseURL = http://localhost:3333 
@authToken = {{authentificate.response.body.access_token}}
# @name test_server_conection
GET  {{baseURL}}/create_accounts
Content-Type: application/json
 
###
# @name create_account
POST {{baseURL}}/create_accounts
Content-Type: application/json
 
{
    "name": "Fulaninho",
    "email": "fulaninho123@gmail.com",
    "password": "654243"
}

###
# @name authentificate
POST {{baseURL}}/authenticate
Content-Type: application/json
 
{
    "email": "fulaninha0@gmail.com",
    "password": "654243"
}

###
# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title" : "New Question 3",
    "content" : "New Question Content"
}

###
# @name fetch_questions
GET  {{baseURL}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###